[build]
  base = "project"
  command = "npm install && npm run build"
  publish = "project/dist"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
